### PR TITLE
fix: deprecated main cursus has displayed first

### LINKED ISSUE #479: Wrong cursus displayed on profile
### Describe the bug

Big described on Discord: https://discord.com/channels/248936708379246593/1127551159188602880

### To Reproduce

1. Have two cursus : 42 and 42-cursus
2. Show profile
3. The wrong cursus is displayed

### Expected behavior

The cursus called 42-cursus must be displayed

### Relevant log output

_No response_

### Version of software

v0.27.1

### Environment

Live (https://s42.app)

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by 42atomys**
**Describe the pull request**
This pull request addresses an issue where a deprecated main cursus was being displayed first. The fix involves revising the cursus display order to prioritize current cursus over deprecated ones. Fix #479 

**Checklist**
- [x] I have made the modifications or added tests related to my PR
- [x] I have run the tests and linters locally and they pass
- [x] I have added/updated the documentation for my RP

### CODE REVIEW

File: web/ui/src/components/UserProfile/UserProfile.tsx [hunk 1]
```diff
@@ -49,9 +49,17 @@ const Badges: React.FC<{ flags: UserFlag[] }> = ({ flags }) => {
...
-  const mainCursusUser = intraProxy.cursusUsers?.find(
-    (c) => c.cursus?.kind.includes('main'),
-  );
+  const mainCursusUser =
+    intraProxy.cursusUsers?.find(
+      // Find the main cursus user
+      (c) => c.cursus?.kind === 'main',
+    ) ||
+    intraProxy.cursusUsers?.find(
+      // If no main cursus user is found for the old cursus system, find the
```
Comment (42atomys) [inline web/ui/src/components/UserProfile/UserProfile.tsx:58]:
```suggestion
      // If no main cursus user is found for the new cursus system, find the
```

**Comment by 42atomys** [comment]
Self reviewed ✅
